os:
  - linux
before_install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
before_script:
  - sudo add-apt-repository -y ppa:ubuntu-wine/ppa
  - sudo apt-get update -qq &> /dev/null
  - sudo apt-get install -y binutils-mingw-w64-i686
  - sudo apt-get install -y gcc-mingw-w64-i686 &> /dev/null
  - sudo apt-get install -y wine1.7 &> /dev/null
language: c
compiler:
  - gcc
script:
  - unset CC
  - sudo update-binfmts --disable wine
  - export CC=i686-w64-mingw32-gcc
  - ./Configure gcc
  - make
  - sudo update-binfmts --enable wine
  - wineboot
  - export WINEDEBUG=-all
  - make test (some project use `make check` instead)